name: Sync to GitLab

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 2 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Important: Fetch all history

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          GITLAB_URL: ${{ secrets.GITLAB_URL }}
          GITLAB_NAMESPACE: ${{ secrets.GITLAB_NAMESPACE }}
        run: |
          git remote add gitlab "https://${GITLAB_URL}/${GITLAB_NAMESPACE}/${GITHUB_REPOSITORY}.git"
          echo "Pushing to gitlab remote..."
          git push --mirror "https://oauth2:${GITLAB_TOKEN}@${GITLAB_URL}/${GITLAB_NAMESPACE}/${GITHUB_REPOSITORY}.git"
